### PR TITLE
Renames install-houaphan to install-nutyx

### PR DESCRIPTION
**Pull request by peter1000**
1.
As discussed to keep it more general: probably the README of the other package repositories needs to be also adjusted.

I think it is still worthy, because in the future it will be easier to maintain your documentation.

2. German adjustment

### CODE REVIEW

**Comment by peter1000** [comment]
Maybe of general interest: I started to repos:

* [NuTyX_packages](https://github.com/peter1000/NuTyX_packages)
* [NuTyX-Installer](https://github.com/peter1000/NuTyX-Installer)

**Comment by tnut** [comment]
I guess I will need to wait for this "big impact" change. After investigating a bit, the best would be to rename them at the next major release. As I have seen it's too much connections (at least for me anyway)

**Comment by peter1000** [comment]
no problem at all

**Comment by tnut** [comment]
can You make another pull request with the changes you did beside the renaming ( build-package for ex) I would like to pull it. try to keep one pull request / one file

**Comment by peter1000** [comment]
I hope that is what you wanted: https://github.com/NuTyX/houaphan/pull/25

**Comment by tnut** [comment]
yes but they aresome conflits

**Comment by peter1000** [comment]
I think you looked at the wrong pull request - the other says no conflict. I close this for now so that there is o confusion.

**Pull request closed without merging**
